name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.3.1

      - name: Install Deno
        uses: denoland/setup-deno@v1.5.2
        with:
          deno-version: 2.9.5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2.2.0

      - name: Build step
        run: "bun install && bun run deno:build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@1.13.1
        with:
          project: "waku-rsc"
          entrypoint: "./serve.ts"
          root: "."
